hwpolls/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views

urlpatterns = [
    url(r'^admin/',admin.site.urls),
    url(r'^polls/',include(('polls.urls','polls'),namespace='polls')),
    url(r'^login/', views.LoginView.as_view(template_name='polls/login.html'), name='login'),
    url(r'^logout/', views.LogoutView.as_view(template_name='polls/logout.html'), name='logout')
]

polls/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
url(r'^$', views.IndexView.as_view(), name='index' ), 
url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
url(r'^(?P<pk>[0-9]+)/results$', views.ResultsView.as_view(), name='results'),
url(r'^(?P<question_id>[0-9]+)/vote$', views.vote, name='vote'),
]

polls/models.py
from django.db import models

from django.utils import timezone
import datetime


# Create your models here.

class Question(models.Model):

	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')

	def __str__(self):
		return self.question_text

	def was_published_in_last_7_days(self):
		now = timezone.now()
		return timezone.now() - datetime.timedelta(days=7) <= self.pub_date <= now

	was_published_in_last_7_days.admin_order_field = 'pub_date'
	was_published_in_last_7_days.boolean = True
	was_published_in_last_7_days.short_description = 'Published This Week?'


class Choice(models.Model):

	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)
	question = models.ForeignKey(Question,on_delete=models.CASCADE)

	def __str__(self):
		return self.choice_text

polls/views.py
from django.shortcuts import get_object_or_404, render

from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse

from django.views import generic

from .models import Question, Choice

from django.http import Http404

from django.utils import timezone

# Create your views here.

class IndexView(generic.ListView):
	template_name = 'polls/index.html'
	context_object_name = 'latest_question_list'

	def get_queryset(self):
		return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
	model = Question
	template_name = 'polls/detail.html'

	def get_queryset(self):
		return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
	model = Question
	template_name = 'polls/results.html'

	def get_queryset(self):
		return Question.objects.filter(pub_date__lte=timezone.now())

def vote(request, question_id):

	p = get_object_or_404(Question, pk=question_id)
	try:
		selected_choice = p.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		context = {'question':p, 'error_message': 'You didn\'t select a choice yet.'}
		return render(request, 'polls/detail.html', context)
	else:
		selected_choice.votes += 1
		selected_choice.save()
		return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))

polls/templates/polls/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
 <head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Example Company</title>
   <!-- Bootstrap core CSS -->
   <link href="{% static 'polls/bootstrap-3.3.5-dist/css/bootstrap.min.css' %}" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
 </head>
 <body>
 	<div class='container'>
		{% include "polls/header.html" %}
	 	{% block main_content %}
	 	{% endblock %}
	 	{% include "polls/footer.html" %}
	 </div>
  
 </body>
</html>

polls/templates/polls/detail.html
{% extends "polls/base.html" %}

{% block main_content %}

<h1>{{question.question_text}}</h1>

{% if error_message %}<p><strong>{{error_message}}</strong></p>{% endif %}
{% if user.is_authenticated %}
<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
	  <input type="radio" name="choice"  id="choice{{forloop.counter}}" value="{{choice.id}}"/>
	  <label for="choice{{forloop.counter}}"> {{choice.choice_text}}</label></br>
{% endfor %}
<input type="submit" class="btn btn-success" value="Vote"/>
</form>
{% else %}
<div>MUST BE LOGGED IN</div>
{% endif %}
<br>
<a href="{% url 'polls:index' %}"><< Back To Question List</a>
<br>

{% endblock %}

polls/templates/polls/footer.html
<footer class="footer">
	<p>&copy; Company 2019</p>
</footer>

polls/templates/polls/header.html
<div class="header clearfix">
	<nav>
	  <ul class="nav nav-pills pull-right">



{% if user.is_authenticated %}
  	<li role="presentation" ><a href="#">Welcome, {{ user.get_username }}.</a></li>
	<li role="presentation" class="active"><a href="{% url 'logout' %}">Logout</a></li>
{% else %}
    <li role="presentation" class="active"><a href="/login">Login</a></li>
{% endif %}

	    <li role="presentation"><a href="#">About</a></li>
	    <li role="presentation"><a href="#">Contact</a></li>
	  </ul>
	</nav>
	<h3 class="text-muted">Project name</h3>
</div>

polls/templates/polls/index.html
{% extends "polls/base.html" %}


{% block main_content %}

{% if latest_question_list %}
	<h1>Question list</h1>
	<ul>
		{% for question in latest_question_list %}
			<li><a href='{% url "polls:detail" question.id %}'>{{question.question_text}}</a></li>
		{% endfor %}
	</ul>
{% else %}
	<p>You haven't uploaded any questions yet.</p>
{% endif %}

{% endblock %}

polls/templates/polls/login.html
{% extends 'polls/base.html' %}

{% block title %}Login{% endblock %}

{% block main_content %}
  <h2>Login</h2>
  <form method="post" action="{% url 'login' %}">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit">Login</button>
  </form>
{% endblock %}

polls/templates/polls/logout.html
{% extends 'polls/base.html' %}

polls/templates/polls/results.html
{% extends "polls/base.html" %}

{% block main_content %}

<h1>{{question.question_text}}</h1>
<ul>
	{% for choice in question.choice_set.all %}
		<li>{{choice.choice_text}} -- {{choice.votes}} vote{{choice.votes|pluralize}}</li>
	{% endfor %}
</ul>
{% if user.is_authenticated %}
	<h4><a href="{% url 'polls:detail' question.id %}">Vote again?</a></h4>
{% else %}
  <p>Must be logged in to vote</p>
{% endif %}
<br>

{% endblock %}